Checking CPU Info

In [3]:
#!lscpu
#!free -m # to check ram in MB
! df -h  # to check hard usage

'df' is not recognized as an internal or external command,
operable program or batch file.


In [ ]:
# checking tensorflow 
! pip install tensorflow 
! pip list | grep -i tensorflow 

In [5]:
# checking version
import tensorflow as tf
print(tf.__version__)

2.13.0


In [6]:
# creating tensor vector 
x = tf.constant([1,2,3]) # creatign 
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
# inbuild function using 
y=tf.ones((4,4),dtype='int32')
y1=tf.ones((3,3),dtype=tf.int64)
y2=tf.zeros((2,3))
y3=tf.eye(3) # identity matrix 
y4=tf.range(start=2,limit=20,delta=2)
print(y4)

tf.Tensor([ 2  4  6  8 10 12 14 16 18], shape=(9,), dtype=int32)


In [8]:
# maths is same as numpy 
x1=tf.constant([2,3,4])
x2=tf.constant([5,8,4])
z1=tf.add(x1,x2) # created 3 vector 
print(z1)

tf.Tensor([ 7 11  8], shape=(3,), dtype=int32)


In [9]:
import tensorflow as tf
from tensorflow import keras
import numpy as np 
import matplotlib.pyplot as plt 
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
# ignoring logs of tensorflow 

In [10]:
# creating data
np.random.seed(0) # setting random selection data
x=np.random.rand(100,2)
y=(x[:,0] + x[:,1] > 1).astype(int)     # binary classifier 
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [11]:
# split by maths
ratio1=0.8 
ration1_index=int(len(x) * ratio1)

In [12]:
# traing and testing  of features 
train_x,test_x = x[:ration1_index],x[ration1_index:]
train_y , test_y = y[:ration1_index],y[ration1_index:]

In [13]:
# define Sequential ANN using keras
keras.Sequential()